# Generated by Django 2.0.2 on 2018-03-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('rejected', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
