# Generated by Django 2.0.1 on 2018-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FICSGamesDBGameNo', models.IntegerField()),
                ('BlackElo', models.IntegerField()),
                ('WhiteElo', models.IntegerField()),
                ('Result', models.IntegerField()),
                ('PlyCount', models.IntegerField()),
            ],
        ),
    ]
