# Generated by Django 2.0.1 on 2018-03-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='BlackElo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='FICSGamesDBGameNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='PlyCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='Result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='WhiteElo',
            field=models.IntegerField(null=True),
        ),
    ]
